[build]
base = ''
command = 'npm run build'
publish = 'build'

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[headers]]
for = "/*.pdf"
values = { Cache-Control = "no-store" }

[build.environment]
REACT_APP_SENTRY_DSN = ""
REACT_APP_GA = ""
REACT_APP_SENTRY_ENVIRONMENT = "develop"

[context.production.environment]
REACT_APP_SENTRY_ENVIRONMENT = "production"
